[package]
name = "hosts-setting"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal-menu = "2.0.0"
regex = "1.5.4"
crossterm = "0.20.0"